[features]
seeds = false
[programs.localnet]
solana-twitter = "7Fowfjw4Z1sEDkevGhaaH2r7tPSuE6UfwbBF1p8nPyHj"

[programs.devnet]
solana-twitter = "7Fowfjw4Z1sEDkevGhaaH2r7tPSuE6UfwbBF1p8nPyHj"

[programs.mainnet]
solana-twitter = "7Fowfjw4Z1sEDkevGhaaH2r7tPSuE6UfwbBF1p8nPyHj" 

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/loktioncode/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
